calmm-js/partial.lenses

README.md, src/partial.lenses.js
Rewrote find and firstOf using choose.
=> Added append and choose.

CHANGELOG.md, README.md, bench/bench.js, package.json, src/partial.lenses.js, test/tests.js
Reimplemented traversals using static land style dictionaries.  ~The
implementation is currently not fully static land compliant, however.~
Dropped Ramda dependency and started using infernals.
=> Towards full traversal support.

CHANGELOG.md, README.md, package.json, src/partial.lenses.js, test/core.js, test/tests.js, test/type.js, test/types.js
=> Indexed optics

README.md, src/partial.lenses.js, test/core.js, test/tests.js, test/types.js
Thanks to @istonikula for asking the right question!
=> Introduce a new combinator to help implement propagating remove

README.md, bench/bench.js, src/partial.lenses.js, test/core.js, test/tests.js, test/types.js
PR to get CI feedback. Not to be merged lightly!
=> Experimental transforms with monadic sequencing

README.md, bench/bench.js, src/partial.lenses.js, test/core.js, test/tests.js, test/types.js
An approach to #56 
PR to get CI feedback
=> WIP: Experimental lazy traversals

CHANGELOG.md, README.md, src/partial.lenses.js, test/core.js, test/tests.js, test/types.js
Towards next major release.  (closes #56)
=> Drop obsolete features.  Don't call laziness experimental #56.

CHANGELOG.md, README.md, src/partial.lenses.js, test/core.js, test/tests.js, test/type.js, test/types.js
=> WIP Freezing

README.md, scripts/generate-docs, src/partial.lenses.js, test/core.js, test/tests.js, test/types.js
=> WIP RegExp optics

CHANGELOG.md, README.md, package.json, src/partial.lenses.js, test/tests.js, test/type.js, test/types.js
This is technically a breaking change if merged, but is unlikely to affect many users.
=> Experiment to switch (mostly internal) order of args to improve get performance

README.md, src/partial.lenses.js, test/tests.js, test/types.js
I couldn't come up with a good name.  Nevertheless I believe this is a useful and theoretically solid addition.  Naming suggestions are welcome!
=> Add a combinator to create a lens from a fold and a traversal

README.md, src/partial.lenses.js, test/tests.js, test/types.js
Now we'd have `all`, `any`, and `none`.  What would be a nice name for the
fourth and still missing variant?
Addresses #90
=> Add `none`

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Generalizing `branch` and `pick` to accept nested templates

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Adding `pickIn` combinator

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Adding `array` iso constructor

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Add `reread`

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Add `counts` and `countsAs`

CHANGELOG.md, README.md, bench/bench.js, src/partial.lenses.js, test/tests.js, test/types.js
WIP
* ~consider supporting [naked objects](https://glebbahmutov.com/blog/sweet-naked-objects/)~ *later*
=> Version 12.0.0

CHANGELOG.md, EXERCISES.md, README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Drop dy default removal of empty arrays, objects, and strings

CHANGELOG.md, README.md, src/contract.js, src/partial.lenses.js, test/tests.js, test/types.js
=> Added `ifElse` and `cond` to replace `iftes`.  Added `first`.

README.md, src/ext/infestines.js, src/partial.lenses.js, test/tests.js, test/types.js
=> Added `dropPrefix`, `dropSuffix`, `replaces`, `split`, `uncouple`

CHANGELOG.md, README.md, src/partial.lenses.js, test/tests.js
=> Avoid cloning in traversals

README.md, package-lock.json, package.json, src/partial.lenses.js, test/.babelrc, test/tests.js, test/type.js, test/types.js
Provides minimal async support.  Closes #151.
=> Added `modifyAsync` and `transformAsync`

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Added `joinIx`, `mapIx`, `setIx`, `skipIx`, and `tieIx`

CHANGELOG.md, README.md, bench/bench.js, src/partial.lenses.js, test/tests.js, test/types.js
=> Switched `get` from `Constant` functor to `Select` applicative

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Added `multikeyed`

CHANGELOG.md, README.md, src/partial.lenses.js, test/tests.js, test/type.js
Closes #187 
Closes #163 (close enough for now)
=> Avoid throwing by passing along the error instead

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Added `querystring`

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Fantasy Land interop

README.md, src/partial.lenses.js, test/tests.js, test/types.js
=> Added `disperse`, `partsOf`, `collectTotal`, and `collectTotalAs`

README.md, package-lock.json, package.json, src/ext/infestines.js, src/partial.lenses.js, test/.babelrc, test/lambda.js, test/ppp.js, test/tests.js, test/types.js
Inspired by #167 
* ~Support nesting/applying isomorphisms~ Will be considered as a backwards compatible addition later on.
=> Added `L.mapping` and `L.mappings`
